name: Tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for tags

      - name: Bump version and create tag
        id: tag
        run: |
          # Get latest tag or default to v0.0.0
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Extract version numbers
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"

          # Increment patch version
          new_tag="v$major.$minor.$((patch+1))"

          echo "new_tag=$new_tag" >> $GITHUB_ENV

          # Create and push new tag
          git tag $new_tag
          git push origin $new_tag

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
            daemon-config: |
              {
                 "debug": true,
                 "features": {
                   "containerd-snapshotter": true
                 }
              }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log into Container
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
